In [39]:
import urllib
import requests
import numpy as np
import math

# Übungsblatt 2

## Aufgabe 2.1 
### Komplexität von Matrix-Operationen
Bestimmen Sie die Laufzeitkomplexität der folgenden Operationen für Matrizen $A, B ∈ R$, 
$n×n$:

a) Addition A + B 

b) Multiplikation A · B

c) det(A) mit Laplaceschem Entwicklungssatz

d) det(A) nach Vereinfachung (’viele Nullen’, ähnlich Gauß)

### Lösung:

a) Eine skaralare Addition beanspruche die Zeit $t_1$, der Zugriff auf eine Zahl $t_2$ und die Zuweisung $t_3$.
   Dann ergibt sich für die Addition zweiter Matritzen: $t = n^2(t_1+2t_2 +t_3)$
   Die Laufzeitkomplexität ist folglich $\mathcal{O}(n^2)$.
   
b) Eine skaralare Multiplikation beanspruche die Zeit $t_0$, Eine skaralare Addition beanspruche die Zeit $t_1$, der     Zugriff auf eine Zahl $t_2$ und die Zuweisung $t_3$.
   Dann ergibt sich für die Multiplikation zweiter Matritzen: $t = n^2t_3 + n^2(2t_2+t_1)+ n^3(t_0+2t_2) $
   Die Laufzeitkomplexität ist folglich $\mathcal{O}(n^3)$.
   
c) Der Laplacesche Entwicklungsatz basiert darauf die Determinante einer Matrix durch Determinanten von Teilmatrizen auszurechnen. Dabei wird immer jeweils über eine Spalte oder Zeile entwickelt um die Determinante auf n Matrizen aufzuteilen.
Ist man beim Laplaceschen Entwicklungssatz bei einer $2x2$ Matrix angekommen, setzt man in die Definition der Determinante ein und erhält 

$det(A) = ac-bd$

Für 

$A = \begin{pmatrix}
  a & b\\ 
  c & d
\end{pmatrix}$

Um diese $2x2$ Determinante auszurechen wird eine konstante Zeit $t_0$ angenommen. Bei steigendem n kann die Zeit wie folgt appoximiert werden: $t = \frac{n!}{2} \cdot t_0$. Selbstverständlich benötigt auch das Entwickeln selbst bei steigender Größe der Matrix Zeit, allerdings ist diese im Vergleich zum berechnen der 2x2 Determianten vernachlässigbar.
Die Laufzeitkomplexität ist $\mathcal{O}(n!)$.


   

## Aufgabe 2.2 
### Komplexität des Gaußschen-Eliminationsverfahrens

Bestimmen Sie Komplexitätsklasse von Laufzeit und Speicher der Gauß-Elimination für ein $n×n$-LGS.


### Lösung:

#### Speicher:
Es wird jeweils die Matrix gespeichert und eine Zeile bzw. Spalte, um Vielfache von Zeilen/Spalten zu addieren/subtrahieren.
Folglich ist die Komplexitätsklasse $\mathcal{O}(n^2)$.
#### Laufzeit:
Für die berechnung der Laufzeit wird der Worst Case angenommen, dh. dass die Zeilenstufenform durch Elimination jedes einzelnen Matrixelements hergestellt werden muss.

Werfen wir zunächst einen Blick auf den Klassischen Gauß Algorithmus:

In [27]:
def elimination (a, b):
    n = a.shape [0]
    for i in range(n):                         # n-Maliges durchführen
        for j in range (i +1 , n):             # n^2 maliges Durchführen
            faktor = a [j, i]/ a[i, i]
            b[j] -= b[i]* faktor
            for k in range (i , n ):           # n^3 maliges Durchführen
                a[j, k] -=a[i, k]*faktor
def substitution (a, b):
    n = a.shape [0]
    x = np.empty(n)
    for i in range (n -1 , -1 , -1):
        zaehler = b[i]
    for j in range (i +1, n):
        zaehler -= a[i, j]*x[j]
        x[i] = zaehler/a[i, i]
    return x

a = np.array([[2 ,3 ,1] ,[4 ,7 ,3] ,[2 ,4 ,4]] , dtype = float)
b = np.array([1 ,2 ,2], dtype=float)

print("a Vor Elimination:")
print(a)
print("b vor Elimination:")
print(b)
elimination (a, b)
print("a Nach Elimination:")
print(a)
print("b Nach Elimination:")
print(b)
substitution (a, b)

a Vor Elimination:
[[2. 3. 1.]
 [4. 7. 3.]
 [2. 4. 4.]]
b vor Elimination:
[1. 2. 2.]
a Nach Elimination:
[[2. 3. 1.]
 [0. 1. 1.]
 [0. 0. 2.]]
b Nach Elimination:
[1. 0. 1.]
a Nach Sub:
[[2. 3. 1.]
 [0. 1. 1.]
 [0. 0. 2.]]
b Nach Sub:
[1. 0. 1.]


Den Überlegungen aus den Kommentaren kann entnommen werden, dass die Komplexität der Laufzeit der Gauß Elimination $\mathcal{O}(n^3)$ ist.

## Aufgabe 2.3 
### TSP

Finden Sie die (möglichst) optimale Route durch die Punkte aus der Datei tsp01.data.

Neigrest Neigbor Ansatz:

In [62]:
f = open("tsp01.data","r")
points = []
#Berechnet die Distanz zwischen zwei Punkten
def distance(p,q):
    return math.sqrt((p[0]-q[0])**2+(p[1]-q[1])**2)
for el in f.readlines():
    #Einlesen der Punkte
    points.append([float(el.split()[0]),float(el.split()[1]), False]) #False signalisiert, dass Punkt nicht besucht wurde.
#Neigrest Neigbor

#starte beim ersten Element
indexAktiv = 0
nextPoint = 0
reihenfolge = [0]
while True:
    points[indexAktiv][2] = True
    #berechne distanz
    nextDis = 0
    tmpDis = 1000000
    shouldBreak = True
    for el in range(len(points)):
        if(not points[el][2]):
            shouldBreak = False
            nextDis = distance(points[indexAktiv],points[el])
            #print(nextDis)
            if(nextDis<tmpDis):
                tmpDis = nextDis
                nextPoint = el
    if shouldBreak:
        break
    points[nextPoint][2] = True
    reihenfolge.append(nextPoint)
print("Die Reihenfolge ist:")
print(reihenfolge)
f.close()

Die Reihenfolge ist:
[0, 14, 7, 13, 3, 6, 5, 8, 2, 9, 10, 1, 4, 12, 11]


## Aufgabe 2.4 
### Rucksack-Problem I
Verwenden Sie ein Verfahren Ihrer Wahl um einen Rucksack mit 500 kg Tragkraft optimal mit folgenden [Gegenständen](http://rosettacode.org/wiki/Knapsack_problem/0-1) zu füllen:

<table><thead><tr><th>item</th><th>Gewicht</th><th>Wert</th><th rowspan="13"></th><th>item</th><th>Gewicht</th><th>Wert</th></tr><tr><td>map</td><td>9</td><td>150</td><td>T-shirt</td><td>24</td><td>15</td></tr><tr><td>compass</td><td>13 </td><td>35</td><td>trousers</td><td>48</td><td>10</td></tr><tr><td>water</td><td>153</td><td>200</td><td>umbrella</td><td>73</td><td>40</td></tr><tr><td>sandwich</td><td>50</td><td>160</td><td>waterproof trousers</td><td>42</td><td>70</td></tr><tr><td>glucose</td><td>15</td><td>60</td><td>waterproof overclothes</td><td>43</td><td>75</td></tr><tr><td>tin</td><td>68</td><td>45</td><td>note-case</td><td>22</td><td>80</td></tr><tr><td>banana</td><td>27</td><td>60</td><td>sunglasses</td><td>7</td><td>20</td></tr><tr><td>apple</td><td>39</td><td>40</td><td>towel</td><td>18</td><td>12</td></tr><tr><td>cheese</td><td>23</td><td>30</td><td>socks</td><td>4</td><td>50</td></tr><tr><td>beer</td><td>52</td><td>10</td><td>book</td><td>30</td><td>10</td></tr><tr><td>suntan cream</td><td>11</td><td>70</td><td>notebbok</td><td>90</td><td>1</td></tr><tr><td>camera</td><td>32</td><td>30</td><td>tent</td><td>200</td><td>150</td></tr></thead></table>

### Brute force

In [31]:
from itertools import combinations
 
def anycomb(items):
    ' Retured alle möglichen Kombinationen verschiedener Länge'
    return ( comb
             for r in range(1, len(items)+1)
             for comb in combinations(items, r)
             )
 
def totalvalue(comb):
    ' Totalise a particular combination of items'
    totwt = totval = 0
    for item, wt, val in comb:
        totwt  += wt
        totval += val
    return (totval, -totwt) if totwt <= 500 else (0, 0)
 
items = (
    ("map", 9, 150), ("compass", 13, 35), ("water", 153, 200), ("sandwich", 50, 160),
    ("glucose", 15, 60), ("tin", 68, 45), ("banana", 27, 60), ("apple", 39, 40),
    ("cheese", 23, 30), ("beer", 52, 10), ("suntan cream", 11, 70), ("camera", 32, 30),
    ("t-shirt", 24, 15), ("trousers", 48, 10), ("umbrella", 73, 40),
    ("waterproof trousers", 42, 70), ("waterproof overclothes", 43, 75),
    ("note-case", 22, 80), ("sunglasses", 7, 20), ("towel", 18, 12),
    ("socks", 4, 50), ("book", 30, 10),
    )
bagged = max( anycomb(items), key=totalvalue) 
print("Die folgenden Items wurden eingepackt:\n  " +
      '\n  '.join(sorted(item for item,_,_ in bagged)))
val, wt = totalvalue(bagged)
print("mit dem Gesamtwert %i und Gesamtgewicht %i" % (val, -wt))

Die folgenden Items wurden eingepackt:
  apple
  banana
  camera
  cheese
  compass
  glucose
  map
  note-case
  sandwich
  socks
  sunglasses
  suntan cream
  water
  waterproof overclothes
  waterproof trousers
mit dem Gesamtwert 1130 und Gesamtgewicht 490


### Dynamisch

In [13]:
def totalvalue(comb):
    # berechne Gewicht und Wertigkeit einer Kombination
    gesGewicht = gesWert = 0
    for item, wt, val in comb:
        gesGewicht  += wt
        gesWert += val
    return (gesWert, -gesGewicht) if gesGewicht <= 500 else (0, 0)

items = (
    ("map", 9, 150), ("compass", 13, 35), ("water", 153, 200), ("sandwich", 50, 160),
    ("glucose", 15, 60), ("tin", 68, 45), ("banana", 27, 60), ("apple", 39, 40),
    ("cheese", 23, 30), ("beer", 52, 10), ("suntan cream", 11, 70), ("camera", 32, 30),
    ("t-shirt", 24, 15), ("trousers", 48, 10), ("umbrella", 73, 40),
    ("waterproof trousers", 42, 70), ("waterproof overclothes", 43, 75),
    ("note-case", 22, 80), ("sunglasses", 7, 20), ("towel", 18, 12),
    ("socks", 4, 50), ("book", 30, 10),
    )

def knapsackProblem(items, limit):
    table = [[0 for w in range(limit + 1)] for j in xrange(len(items) + 1)]

    for j in xrange(1, len(items) + 1):
        item, wt, val = items[j-1]
        for w in xrange(1, limit + 1):
            if wt > w:
                table[j][w] = table[j-1][w]
            else:
                table[j][w] = max(table[j-1][w],
                                  table[j-1][w-wt] + val)

    result = []
    w = limit
    for j in range(len(items), 0, -1):
        was_added = table[j][w] != table[j-1][w]

        if was_added:
            item, wt, val = items[j-1]
            result.append(items[j-1])
            w -= wt

    return result


eingepackt = knapsackProblem(items, 500)
print("Die folgenden Items wurden eingepackt:\n  " +
      '\n  '.join(sorted(item for item,_,_ in eingepackt)))
val, wt = totalvalue(eingepackt)
print("mit dem Gesamtwert %i und Gesamtgewicht %i" % (val, -wt))


Die folgenden Items wurden eingepackt:
  apple
  banana
  camera
  cheese
  compass
  glucose
  map
  note-case
  sandwich
  socks
  sunglasses
  suntan cream
  water
  waterproof overclothes
  waterproof trousers
mit dem Gesamtwert 1130 und Gesamtgewicht 490


### Rekursiv

In [14]:
def total_value(items, max_weight):
    return  sum([x[2] for x in items]) if sum([x[1] for x in items]) <= max_weight else 0
 
cache = {}
def solve(items, max_weight):
    if not items:
        return ()
    if (items,max_weight) not in cache:
        head = items[0]
        tail = items[1:]
        include = (head,) + solve(tail, max_weight - head[1])
        dont_include = solve(tail, max_weight)
        if total_value(include, max_weight) > total_value(dont_include, max_weight):
            answer = include
        else:
            answer = dont_include
        cache[(items,max_weight)] = answer
    return cache[(items,max_weight)]
 
items = (
    ("map", 9, 150), ("compass", 13, 35), ("water", 153, 200), ("sandwich", 50, 160),
    ("glucose", 15, 60), ("tin", 68, 45), ("banana", 27, 60), ("apple", 39, 40),
    ("cheese", 23, 30), ("beer", 52, 10), ("suntan cream", 11, 70), ("camera", 32, 30),
    ("t-shirt", 24, 15), ("trousers", 48, 10), ("umbrella", 73, 40),
    ("waterproof trousers", 42, 70), ("waterproof overclothes", 43, 75),
    ("note-case", 22, 80), ("sunglasses", 7, 20), ("towel", 18, 12),
    ("socks", 4, 50), ("book", 30, 10),
    )
max_weight = 500
 
solution = solve(items, max_weight)
print ("items:")
for x in solution:
    print (x[0])
print ("value:" + str(total_value(solution, max_weight)))
print ("weight:" + str(sum([x[1] for x in solution])))

items:
map
compass
water
sandwich
glucose
banana
apple
cheese
suntan cream
camera
waterproof trousers
waterproof overclothes
note-case
sunglasses
socks
value:1130
weight:490


## Aufgabe 2.5 
### Rucksack-Problem II

Verwenden Sie dynamische Programmierung oder einen branch-and-bound-Ansatz um eine möglichst
gute Füllung für einen Rucksack mit 10 000 g Tragkraft aus Objekten der Datei knapsack01.data
zu finden (Gewichte in Gramm).

Überprüfen Sie Ihr Ergebnis mit Ihrem Algorithmus aus Aufgabe 2.4.

In [30]:
def totalvalue(comb):
    # berechne Gewicht und Wertigkeit einer Kombination
    gesGewicht = gesWert = 0
    for item, wt, val in comb:
        gesGewicht  += wt
        gesWert += val
    return (gesWert, -gesGewicht) if gesGewicht <= 10000 else (0, 0)

file_object  = open("knapsack01.data", "r") 
contents =file_object.readlines()
items = []
for row in contents[1:]:
    items.append((row.split()[0],int(row.split()[1]),int(row.split()[2])))
items = tuple(items)

file_object.close()

def knapsackProblem(items, limit):
    table = [[0 for w in range(limit + 1)] for j in xrange(len(items) + 1)]

    for j in xrange(1, len(items) + 1):
        item, wt, val = items[j-1]
        for w in xrange(1, limit + 1):
            if wt > w:
                table[j][w] = table[j-1][w]
            else:
                table[j][w] = max(table[j-1][w],
                                  table[j-1][w-wt] + val)

    result = []
    w = limit
    for j in range(len(items), 0, -1):
        was_added = table[j][w] != table[j-1][w]

        if was_added:
            item, wt, val = items[j-1]
            result.append(items[j-1])
            w -= wt

    return result


eingepackt = knapsackProblem(items, 10000)
print("Die folgenden Items wurden eingepackt:\n  " +
      '\n  '.join(sorted(item for item,_,_ in eingepackt)))
val, wt = totalvalue(eingepackt)
print("mit dem Gesamtwert %i und Gesamtgewicht %i" % (val, -wt))

Die folgenden Items wurden eingepackt:
  100
  101
  102
  103
  104
  105
  106
  107
  110
  112
  114
  117
  118
  119
  123
  124
  125
  126
  128
  129
  13
  131
  133
  134
  136
  138
  141
  143
  145
  146
  147
  148
  15
  151
  152
  155
  157
  158
  159
  161
  162
  163
  168
  169
  17
  170
  172
  173
  175
  176
  179
  180
  181
  182
  183
  184
  185
  186
  187
  188
  192
  194
  195
  198
  199
  2
  200
  24
  25
  26
  27
  28
  3
  30
  31
  32
  33
  36
  38
  4
  40
  43
  44
  45
  48
  49
  5
  50
  51
  52
  55
  57
  59
  6
  61
  63
  64
  65
  69
  7
  70
  71
  72
  73
  76
  78
  79
  8
  80
  81
  82
  83
  86
  89
  93
  94
  95
  97
  99
mit dem Gesamtwert 77876 und Gesamtgewicht 10000
